Carrossel/Endentação
Lucaspinto12/PITU pull request #6
Opened 2024-08-16 00:58 UTC by FerFrizoni

Tirei o carrossel e mexi na endentação do rodapé da página

2024-08-16 17:39 UTC, Lucaspinto12 commented
endentação é fd kkkkkkkkk

2024-08-16 17:52 UTC, Lucaspinto12 requested changes

2024-08-16 17:52 UTC, Lucaspinto12 commented on pitu/index.html
> +    <head>
pq tem outro head?

2024-08-16 17:52 UTC, Lucaspinto12 commented on pitu/index.html
> +        height: 100px;
e esse codigo q faz o carrocel ficar enorme

2024-08-16 19:04 UTC, FerFrizoni commented on pitu/index.html
> +        height: 100px;
isso ai foi um provisório, tentamos tirar todo o código do carrossel e a pagina ficou toda desconfigurada, desta forma ela só desaparece.

2024-08-20 14:55 UTC, Lucaspinto12 approved these changes

2024-08-20 14:55 UTC, merged